FROM alpine:3.23 as alpine
RUN apk add -U --no-cache ca-certificates

FROM alpine:3.23
ENV GODEBUG netdns=go
ENV CI=true
COPY --from=alpine /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

ARG JF_CLI_VERSION=2.118.0

RUN apk add --update \
    curl \
    && rm -rf /var/cache/apk/*
RUN curl -fL "https://releases.jfrog.io/artifactory/jfrog-cli/v2-jf/${JF_CLI_VERSION}/jfrog-cli-linux-amd64/jf" \
    -o /usr/local/bin/jfrog && \
    chmod +x /usr/local/bin/jfrog

ADD release/linux/amd64/plugin /bin/
ENTRYPOINT ["/bin/plugin"]
