FROM arm64v8/alpine:3.22 as alpine
RUN apk add -U --no-cache ca-certificates


FROM arm64v8/alpine:3.22

ENV GODEBUG netdns=go
COPY --from=alpine /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

# Install jfrog cli latest version
RUN apk add --update \
    curl \
    && rm -rf /var/cache/apk/*
RUN curl -fL https://getcli.jfrog.io/v2-jf | sh
RUN mv ./jf /usr/local/bin/jfrog
RUN chmod +x /usr/local/bin/jfrog

ADD release/linux/arm64/plugin /bin/
ENTRYPOINT ["/bin/plugin"]
